# Generated by Django 3.2.2 on 2021-07-13 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=30)),
                ('translation', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=500, null=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('slug', models.SlugField(max_length=30)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dictionary.category')),
            ],
            options={
                'ordering': ('-published',),
            },
        ),
    ]
