# Generated by Django 3.2.2 on 2021-07-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='abbreviation',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='category',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.category'),
        ),
    ]
