# Generated by Django 3.2.2 on 2021-07-13 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20210713_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
