# Generated by Django 3.2.2 on 2021-07-13 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_alter_term_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dictionary.category'),
        ),
        migrations.AlterField(
            model_name='term',
            name='term',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
