# Generated by Django 3.2.2 on 2021-07-13 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_auto_20210713_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='abbreviation',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='term',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='term',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
