# Generated by Django 3.2.2 on 2021-07-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_alter_term_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='abbreviation',
        ),
        migrations.RemoveField(
            model_name='term',
            name='translation',
        ),
        migrations.CreateModel(
            name='EnglishTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(blank=True, default='', max_length=30)),
                ('abbreviation', models.CharField(blank=True, default='', max_length=30)),
                ('korean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dictionary.term')),
            ],
        ),
    ]
