# Generated by Django 3.2.2 on 2021-07-13 21:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_auto_20210713_0605'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='englishterm',
            managers=[
                ('translationObjects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='englishterm',
            name='korean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dictionary.term'),
        ),
    ]
