# Generated by Django 3.2.2 on 2021-07-13 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_auto_20210713_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishterm',
            name='korean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dictionary.term', to_field='term'),
        ),
    ]
