# Generated by Django 3.2.2 on 2021-07-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_alter_englishterm_korean'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishterm',
            name='korean',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='dictionary.term'),
        ),
    ]
