# Generated by Django 3.2.2 on 2021-07-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_alter_englishterm_korean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='description',
        ),
        migrations.AddField(
            model_name='englishterm',
            name='description',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
