# Generated by Django 3.2.2 on 2021-07-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_auto_20210713_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishterm',
            name='abbreviation',
            field=models.CharField(blank=True, default='Not available', max_length=30),
        ),
    ]
