# Generated by Django 3.2.2 on 2021-07-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_alter_englishterm_abbreviation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='category',
        ),
        migrations.AddField(
            model_name='term',
            name='category',
            field=models.ManyToManyField(to='dictionary.Category'),
        ),
    ]
